---

 - name: Add kubernetes repo
   yum_repository:
     name: Kubernetes
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
     gpgcheck: yes
     enabled: yes
     repo_gpgcheck: yes
     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

 - name: Install kubectl
   yum:
     name: kubectl
     state: present

 - name: Add kops user
   user:
     name: kops
     comment: KOPs user
     uid: 1002


 - name: Download and install kops
   get_url:
     url: https://github.com/kubernetes/kops/releases/download/1.10.0/kops-linux-amd64
     owner: kops
     dest: /usr/local/bin/kops
     mode: 0770
