---

 - name: Add kubernetes repo
   yum_repository:
     name: Kubernetes
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
     gpgcheck: yes
     enabled: yes
     description: kubenetes repo
     repo_gpgcheck: yes
     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

 - name: import gpg key
   rpm_key:
     key: "{{ item }}"
     state: present
   with_items:
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
   register: import_key
                                                                                                       
 - name: Make cache
   command: "yum -q makecache -y --disablerepo='*' --enablerepo='Kubernetes'"
   when: import_key.changed


 - name: Install kubectl
   yum:
     name: kubectl
     state: present

 - name: Add kops user
   user:
     name: kops
     comment: KOPs user
     uid: 1002

 - name: Download and install kops
   get_url:
     url: https://github.com/kubernetes/kops/releases/download/1.10.0/kops-linux-amd64
     owner: kops
     dest: /usr/local/bin/kops
     mode: 0770
