---
 - name: Check if template file exists
   stat:
     path: /etc/systemd/system/consul.service
   register: consul_service

 - name: Copy template file
   template:
     src: consul_service.j2
     dest: /etc/systemd/system/consul.service
   when: consul_service.stat.exsits == False

