---

 - name: Gather ec2 facts
   ec2_facts:

 - name: make consul configuration directory
   file:
    path: /etc/conf.d
    owner: root
    group: root
    mode: 0755
    state: directory

 - name: Copy template file
   template:
     src: consul.j2
     dest: /etc/conf.d/consul.conf

